config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show]
  resources :articles                       do
    resources :likes, only: [:index,:create, :destroy]
  end
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user,dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :article, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_articles, through: :likes, source: :article

  def like?(article)
    self.likes.exists?(article_id: article.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :self])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
    @articles = Article.all
    @article = Article.new
    @like = Like.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(article_id: params[:article_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
 <div class="contents row">
      <h3>
        編集
      </h3>
    <%= form_with(model: @article, url: article_path, method: :patch) do |f| %>
      <div class="field">
      <%= f.label :content %>
      <%= f.text_field :content, id: :content %><br/>
      </div>
      <%= f.submit %>
    <% end %>
</div>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <h5 class = "submit">投稿する</h5>
  <%= form_for @article do |f| %>
    <%= f.text_field :content, :placeholder => "New article" %>
    <%= f.submit %>
  <% end %>
  <hr>
  <h5>投稿一覧</h5>
  <% @articles.each do |post| %>
        <div class="row">
          <div class="col s12">
            <div class="card blue-grey darken-1">
              <div class="card-content white-text">
                <font ><span class="card-title"><a href="/users/<%= post.user.id %>"><%= post.user.name %></a></span></font>
                  <p><%= simple_format(post.content) %></p>
                  <% if current_user.like?(post) %>
                    <%= button_to 'いいね削除', "/articles/#{post.id}/likes/id", method: :delete, class:"liked" %>
                  <% else %>
                    <%= button_to 'いいね', article_likes_path(post), class:"unlike"  %>
                  <% end %>
                  <% if current_user.id == post.user_id %>
                  <%= button_to '編集', "/articles/#{post.id}/edit", method: :get, class:"edit" %>
                  <%= button_to '削除', "/articles/#{post.id}", method: :delete, class:"delete" %>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% else %>
  <h5>投稿一覧</h5>
  <% @articles.each do |post| %>
        <div class="row">
          <div class="col s12">
            <div class="card blue-grey darken-1">
              <div class="card-content white-text">
                <font ><span class="card-title"><a href="/users/<%= post.user.id %>"><%= post.user.name %></a></span></font>
                  <p><%= simple_format(post.content) %></p>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/articles/show.html.erb
<h4>投稿詳細ページ</h4>
<h5><%= @article.user.email %></h5>
<h5><%= @article.content %></h5>
<%= link_to "ホームへ戻る", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "cyan lighten-5">

<nav class = "blue-grey darken-3">
  <div class="nav-wrapper">
    <a class="brand-logo">Kblog</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li><%=current_user.name%>でログイン中</li>
        <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
      <% else %>
        <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
      <div class="container">
        <!-- Page Content goes here -->

    <%= yield %>
      </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.name %></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", articles_path %>

app/views/users/show.html.erb
<h2>ユーザー詳細ページ</h2>
<h3><%= @user.name %></h3>

<h6>投稿内容</h6>
<% @user.article.each do |post| %>
        <div class="row">
          <div class="col s12">
            <div class="card blue-grey darken-1">
              <div class="card-content white-text">
                <font ><span class="card-title"><a href="/users/<%= post.user.id %>"><%= post.user.name %></a></span></font>
                  <p><%= simple_format(post.content) %></p>
                  <% if user_signed_in? && current_user.id == post.user_id %>
                  <%= link_to '編集', "/articles/#{post.id}/edit", method: :get %>
                  <%= link_to '削除', "/articles/#{post.id}", method: :delete %>
                  <% end %>
              </div>
            </div>
          </div>
        </div>
<% end %>
  <h3>いいねしている投稿</h3>
  <% @user.likes.each do |post| %>
          <div class="row">
            <div class="col s12">
              <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                  <font ><span class="card-title"><a href="/users/<%= post.user.id %>"><%= post.article.user.name %></a></span></font>
                    <p><%= simple_format(post.article.content) %></p>
<!--                     <% if user_signed_in? && current_user.id == post.article.user_id %>
                    <%= link_to '編集', "/articles/#{post.id}/edit", method: :get %>
                    <%= link_to '削除', "/articles/#{post.id}", method: :delete %>
                    <% end %> -->
                </div>
              </div>
            </div>
          </div>
  <% end %>
<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", articles_path %>